project:
  type: website
  output-dir: docs

website:
  title: "Scott Townsend"
  description: "This is Scott Townsend's personal Blog."
  navbar:
    right:
      - about.qmd 
      - href: projects.qmd
        text: Projects
      - text: Resume
        href: files/resume.pdf
      - icon: github
        href: https://github.com/scotty369
      - icon: linkedin
        href: https://www.linkedin.com/in/scott-townsend-0ab515262/
html:
    theme: journal
    css: styles.css



