project:
  type: website

website:
  title: "Scott Townsend"
  description: "This is Scott Townsend's personal Blog."
  navbar:
    right:
      - text: Blog
        href: about.qmd 
      - icon: github
        href: https://github.com/scotty369
format:
  html:
    theme: cosmo
    css: styles.css



